travis:
  secure:
    BINSTAR_TOKEN: akTfEkF9WJlqUR32J0sW9BqxyhU6WINmaW3e17C5dNl+vpVD+2INzSC6gtEOJU7ZxNPsbMzYksAuXNowsTLliuFfCT3qhK+zSZ9LaUPJI6pYubI3r6uqSL3EVItOg8bKkjFsaDyyqzchPWBE+d8XBU8ev2Qqd/QTYdsimuCokQyltdj17jLjzrGDV4POA0VvczovgJ/J8WBWTOw02avwmqEgjt0gFMGNR5n9YLsIAm0cS9/hOE9MXEb4ri0hplExJCX4WskGIINHbt3g9RgAaWCJpC9rXeuepvbfuLIvkopgGuxzn5VHlQfuVBodBUkTTjWjdVqQs7qQl8E9qLxQ3UcM+3PQTMHo1qlT+ICOZ5uol0Oi5OzSl7g1AfoPrO4SoUJ/QhReYRUlipcmsVrrjuyiPXWyn/0ah0EKdisbmCQZmbwaRXXgWL6WmY2a8VMbbyrxYSwSRAljyzP0fU0lrDd4dfnoYbXWIsgIGkU3pQ0MEcnzoux1TsisGYfuFSsDJt6cGuXujT+0cKpD096wOoJ7ZbeM2I8abCZXCEKg8UIzn4pHUK5dh2YhzjqaLyZ1zhHIyZxUyi8PtHWMq1YNq0dFL2Ha4PtkPKhSzAPFiGlP+25link+4yFllphEGvPeNiUv3JHm7qq0wrzxmfWfj05LT7IGEELyFziim7DvkLE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
