travis:
  secure:
    BINSTAR_TOKEN: s3DMCz5vJHeunPvM5jCsAYzXxBLvTQSeeEFbrCe1INCKaNxKSuYMo5R+bGHgqOV1HwrOXtSc1uKcrRI0X058q5PT9E0E4BxfXH8Up8luLT9dT1HhmOWUuoctR7kZRe6S2hO9JgN0xQxUGYh0hyfyiSXQ6s5at4CMBGUF+w9WztZPAm+qUlUI11GLHAVUw3Z/cuXqNP4UQotmQhR9AhdKZOjac6g0N9NitSrGsLiR57rhO12+9V/WquCjYOipyJueDFUo70JFQmm0RYXIN54QmC0ye5aGAoVVUsWzhH8J27t/HXXvUWcXBqbG5QplxpoJyS/ZlgIpt4Vtrne4WGZ3Ik0dWkmefIFI3A+Ebx3+dJ37ZhPn8udiR2EhFTM3d1DkbSujbU5AoR31SqylZtUmw1JFL1Vhx2QhyVDQc2kqLzceIgl8w4473dHHfRNY/OExhsF1FTT5F5d2qWVa6/tg61JJ8t1yrhPRsMJ18Uld3DOhOCWqdUi1hozIuI2v+qdIbV404FYrzds4ITErjq//6SwlE+8j+n1VeEdnu6CZYao2xXcIU6BjJuqi26dN4tz92zA2k2bAg9m28dyKVX3B9kGWUEDBx3cumaevOPk2gvHnZLTgB4unWkB0vXKkIoKQB21OfEo0xMOAH5mO3lEld+/K31pkiLjyBrIx6gR0bQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
